//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Anime')
export class AnimeEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  genre: string;

  @Column('text', { nullable: true })
  description: string;

  @Column('integer', { nullable: true })
  releaseYear: number;

  @Column('real', { nullable: true })
  rating: number;

  @Column('integer', { nullable: true })
  numberOfEpisodes: number;

  @Column('text', { nullable: true })
  studio: string;

  @Column('text', { nullable: true })
  director: string;

  @Column('text', { nullable: true })
  mainCharacters: string;

  @Column('text', { nullable: true })
  imagePoster: string;
}
