//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Rating')
export class RatingEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  finalRating: number;

  @Column('date', { nullable: true })
  ratingDate: Date;

  @Column('integer', { nullable: true })
  userID: number;

  @Column('integer', { nullable: true })
  animeID: number;

  @Column('text', { nullable: true })
  reviewText: string;

  @Column('integer', { nullable: true })
  likesDislikes: number;

  @Column('bool', { nullable: true })
  spoilerWarning: boolean;
}
