//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('User')
export class UserEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  username: string;

  @Column('text', { nullable: true })
  email: string;

  @Column('text', { nullable: true })
  password: string;

  @Column('text', { nullable: true })
  fullName: string;

  @Column('date', { nullable: true })
  dateOfBirth: Date;

  @Column('text', { nullable: true })
  gender: string;

  @Column('text', { nullable: true })
  countryRegion: string;

  @Column('text', { nullable: true })
  profilePicture: string;

  @Column('integer', { nullable: true })
  favoriteAnimeList: number;

  @Column('text', { nullable: true })
  languagePreferences: string;
}
