//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const UserTitle = () => {
  const record = useRecordContext();
  return <span>User {record ? `"${record.username}"` : ''}</span>;
};

export const UserList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="username" />
      <EmailField source="email" />
      <ReadOnlyPasswordField source="password" />
      <TextField source="fullName" />
      <DateField source="dateOfBirth" />
      <TextField source="gender" />
      <TextField source="countryRegion" />
      <ImageField source="profilePicture" />
      <ReferenceField source="favoriteAnimeList" reference="Anime" />
      <TextField source="languagePreferences" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const UserEdit = () => (
  <Edit title={<UserTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="username" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="password" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="fullName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="gender" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="countryRegion" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="profilePicture" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="favoriteAnimeList" reference="Anime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="languagePreferences" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const UserCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="username" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="email" />
        </Grid>
        <Grid item xs={4}>
          <PasswordInput source="password" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="fullName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="gender" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="countryRegion" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="profilePicture" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="favoriteAnimeList" reference="Anime" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="languagePreferences" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="favoriteAnimeList"
    label="favoriteAnimeList"
    reference="Anime"
    alwaysOn
  />,
  ,
];
