//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Anime: {
      name: 'Anime',
      fields: {
        title: 'Title',
        genre: 'Genre',
        description: 'Description',
        releaseYear: 'Release Year',
        rating: 'Rating',
        numberOfEpisodes: 'Number Of Episodes',
        studio: 'Studio',
        director: 'Director',
        mainCharacters: 'Main Characters',
        imagePoster: 'Image Poster',
        id: 'id',
      },
    },
    User: {
      name: 'User',
      fields: {
        username: 'Username',
        email: 'Email',
        password: 'Password',
        fullName: 'Full Name',
        dateOfBirth: 'Date Of Birth',
        gender: 'Gender',
        countryRegion: 'Country Region',
        profilePicture: 'Profile Picture',
        favoriteAnimeList: 'Favorite Anime List',
        languagePreferences: 'Language Preferences',
        id: 'id',
      },
    },
    Rating: {
      name: 'Rating',
      fields: {
        finalRating: 'Final Rating',
        ratingDate: 'Rating Date',
        userID: 'User Id',
        animeID: 'Anime Id',
        reviewText: 'Review Text',
        likesDislikes: 'Likes Dislikes',
        spoilerWarning: 'Spoiler Warning',
        id: 'id',
      },
    },
    Comment: {
      name: 'Comment',
      fields: {
        commentText: 'Comment Text',
        dateAdded: 'Date Added',
        userID: 'User Id',
        animeID: 'Anime Id',
        spoilerFlag: 'Spoiler Flag',
        userRating: 'User Rating',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Anime: {
      name: 'Anime (fr)',
      fields: {
        title: 'Title (fr)',
        genre: 'Genre (fr)',
        description: 'Description (fr)',
        releaseYear: 'Release Year (fr)',
        rating: 'Rating (fr)',
        numberOfEpisodes: 'Number Of Episodes (fr)',
        studio: 'Studio (fr)',
        director: 'Director (fr)',
        mainCharacters: 'Main Characters (fr)',
        imagePoster: 'Image Poster (fr)',
        id: 'id',
      },
    },
    User: {
      name: 'User (fr)',
      fields: {
        username: 'Username (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        fullName: 'Full Name (fr)',
        dateOfBirth: 'Date Of Birth (fr)',
        gender: 'Gender (fr)',
        countryRegion: 'Country Region (fr)',
        profilePicture: 'Profile Picture (fr)',
        favoriteAnimeList: 'Favorite Anime List (fr)',
        languagePreferences: 'Language Preferences (fr)',
        id: 'id',
      },
    },
    Rating: {
      name: 'Rating (fr)',
      fields: {
        finalRating: 'Final Rating (fr)',
        ratingDate: 'Rating Date (fr)',
        userID: 'User Id (fr)',
        animeID: 'Anime Id (fr)',
        reviewText: 'Review Text (fr)',
        likesDislikes: 'Likes Dislikes (fr)',
        spoilerWarning: 'Spoiler Warning (fr)',
        id: 'id',
      },
    },
    Comment: {
      name: 'Comment (fr)',
      fields: {
        commentText: 'Comment Text (fr)',
        dateAdded: 'Date Added (fr)',
        userID: 'User Id (fr)',
        animeID: 'Anime Id (fr)',
        spoilerFlag: 'Spoiler Flag (fr)',
        userRating: 'User Rating (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
